### ISSUE TITLE
区分用户正常转账跟矿池对无效交易的补发交易

### ISSUE THREAD

**Issue by cscjoke** [Qitmeer/0.9.1-invalid-utxo#6]
当用户地址余额未达到归集阈值时，不会对地址做归集操作但会给用户做入账处理。这部分余额中如果有无效交易，矿池会进行补发，不做区分的话会产生重复充值。要怎么区分矿池补发交易和用户正常转账交易？

**Comment by cscjoke** [comment]
矿池补发操作截止时间是什么时候？理想情况是补发操作截止之后再开充值。

**Comment by cscjoke** [comment]
例如地址: [TmSwPvrn9JnGs9ixJQceu3ozfTQzbKCnUGY](https://explorer.qitmeer.io/address/TmSwPvrn9JnGs9ixJQceu3ozfTQzbKCnUGY?p=1)中的交易3: 1ccdbc6ff5c36980d9ab03864132ccab95401ba5b02fbba3d0aae80551d033e7(输出数量: 1269.12309099)就很可能是对交易1: cfa3c3d4e5f6097324f42b4603bb5937f85da012f69bcc1aa445eedba4617b1f(输出数量: 587.85487983)和交易2: c28d08d4fafcee57de947d3e46baf22f891a0fe4c98c397fcc56dd2e93d7b517(输出数量: 681.26821106)的补发。在我们的充值记录里有交易1、交易2两条充值记录(都已做过入账处理)。如果对交易3做入账处理，就会给用户重复充值。交易1输出数量+交易2输出数量 != 交易3输出数量(有0.0000001)的误差，不确定是网页显示精度问题还是转账少了0.0000001

**Comment by dindinw** [comment]
@cscjoke I think there is no way technologically to tell if the `1ccdbc6ff5c36980d9ab03864132ccab95401ba5b02fbba3d0aae80551d033e7` is a resend of tx `cfa3c3d4e5f6097324f42b4603bb5937f85da012f69bcc1aa445eedba4617b1f` and  `c28d08d4fafcee57de947d3e46baf22f891a0fe4c98c397fcc56dd2e93d7b517` , even the amount of `1cc` == `cfa` + `c28`
only the sender @rlinxy can confirm or deny it in a human manner.  The explorer or node can only tell u if the tx is valid or invalid, nothing more than this.

**Comment by cscjoke** [comment]
> @cscjoke I think there is no way technologically to tell if the `1ccdbc6ff5c36980d9ab03864132ccab95401ba5b02fbba3d0aae80551d033e7` is a resend of tx `cfa3c3d4e5f6097324f42b4603bb5937f85da012f69bcc1aa445eedba4617b1f` and `c28d08d4fafcee57de947d3e46baf22f891a0fe4c98c397fcc56dd2e93d7b517` , even the amount of `1cc` == `cfa` + `c28`
> only the sender @rlinxy can confirm or deny it in a human manner. The explorer or node can only tell u if the tx is valid or invalid, nothing more than this.

ok, can @rlinxy provide a resend list?

**Comment by cscjoke** [comment]
thanks
